### ISSUE TITLE
Redirect after save

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#166]
After save user is redirected to list. What do you think about changing this default behavior to redirecting user back to form it edit

**Comment by bartekgruszka** [comment]
In my opinion that kind of behavior should be configurable by options in CRUD elements. See  [`AbstractCRUD`](https://github.com/fsi-open/admin-bundle/blob/master/Admin/CRUD/AbstractCRUD.php) class. I think we should add two new options, for example `redirect_post_create_path` and `redirect_post_edit_path`.

**Comment by norzechowicz** [comment]
Adding that option will not give great benefits and it will took time so I guess its pointless. If somebody need that there are many extension points in admin bundle he can use to achieve that.
