### ISSUE TITLE
Update documentation before 2.0 release

### ISSUE THREAD

**Issue by chives** [fsi-open/admin-bundle#208]
- info about using requirejs
- info about RequestStackAware elements

**Comment by norzechowicz** [comment]
Actually its gonna be 2.0 release

**Comment by chives** [comment]
:+1: for 2.0

**Comment by norzechowicz** [comment]
This is not a blocked - docs can be updated even after 2.0 release

**Comment by norzechowicz** [comment]
I'm closing that ticket, we should create new one with list of things that should be documented and those that already documented.
