### ISSUE TITLE
Adapt to symfony 2.8 and possibly 3.0

### ISSUE THREAD

**Issue by chives** [fsi-open/admin-bundle#212]
We should change symfony dependency on travis from `2.8.*@dev` to `2.8.*` (and probably do not allow failures anymore) and change `dev-master` to `3.0.*` (and hopefully also do not allow failures).

**Comment by norzechowicz** [comment]
Closed by #217 - there is no way to make admin bundle support sf3 in version 2.0. There are too many dependencies in sf3 that should be handled on different levels in different parts of admin panel.
