### ISSUE TITLE
Fix "editable" popup 

### ISSUE THREAD

**Issue by norzechowicz** [fsi-open/admin-bundle#221]
I'm not quite sure why that happens but this is how editable popu looks now: http://prntscr.com/9yu3l3

**Comment by szymach** [comment]
It seems the popover is simply too narrow. I've made it ![wider](https://cloud.githubusercontent.com/assets/2230556/12814438/5e5d544e-cb3f-11e5-9079-69e660c59450.png) to make sure all elements fit.

**Comment by szymach** [comment]
Alright my mistake, I now see it is a matter of removing the collection buttons. This needs to be changed in the datagrid-bundle component, where I will create a custom collection type with it's block ovewritten.

**Comment by norzechowicz** [comment]
ok, this issue should remain open until you fix datagrid-bundle, then we need to update dependency of datagrid bundle to latest version without that bug.
