### ISSUE TITLE
redirect to non-existing page after removing items from last page

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#224]
when user is on last page, selects all elements and delete them, they are redirected to non-existing page and gets exception. maybe the simplest solution is to check if the page is bigger than max and just set last one?

**Comment by szymach** [comment]
Also, as mentioned in #243, we should display a flash message instead of exception if you try to remove 0 elements. Alternatively the batch action form should be prevented from submitting if no elements are checked.

**Comment by szymach** [comment]
It turned out to be a `DataSourceBundle` issue, which will be fixed in [#56](https://github.com/fsi-open/datasource-bundle/pull/56)

**Comment by szymach** [comment]
Resolved by [#56](https://github.com/fsi-open/datasource-bundle/pull/56)
