### ISSUE TITLE
defer resolving admin-element options until first used

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#225]
Currently options are resolved in constructor of [`AbstractElement`](https://github.com/fsi-open/admin-bundle/blob/master/Admin/AbstractElement.php#L32). This prevent for example building options based on resources added by workers (`DoctrineWorker` or `RequestStackWorker`).

Maybe options can be resolved at first use of: `getOption`, `getOptions`, `hasOption`?

**Comment by chives** [comment]
This will be BC break because elements can access `$this->options` directly as long as it is `protected`. We can make it `private` in 3.0

**Comment by szymach** [comment]
Making `$this->options` private will make editing options in children classes impossible, so this change does not resolve the issue.
