### ISSUE TITLE
check permissions to admin-element's only when necessary

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#226]
Currently `SecuredElementInterface:isAllowed` is checked on every request, even when it's not necessary, (eg profiler requests).

Calling it lazily on fetch from `ManagerInterface` would be the best.

**Comment by chives** [comment]
This issue should be moved to https://github.com/fsi-open/admin-security-bundle

**Comment by szymach** [comment]
Closed in favour of [#75](https://github.com/fsi-open/admin-security-bundle/issues/75)
