### ISSUE TITLE
Check permission to model instance

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#228]
... for example when some elements are and some are not ment for edition by current user.  Admin element would check if user is allowed for element what is `edited`/`removed`/`shown`. Maybe we can modify `SecuredElementInterface` somehow?

**Comment by chives** [comment]
This issue should be moved to https://github.com/fsi-open/admin-security-bundle

**Comment by szymach** [comment]
Moved to [#74](https://github.com/fsi-open/admin-security-bundle/issues/74)
