### ISSUE TITLE
randomly failing test on travis

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-bundle#236]
```
--- Failed steps:
    And I should see "News Edit" page header "Edit element" # features/form/nested_collections.feature:12
      Unable to find page header (Exception)
```

**Comment by szymach** [comment]
This is an issue regarding Selenium, somehow the page element is not rendered yet and it fails. Perhaps we could check for the header only in tests not using Javascript to avoid such trivial problems? As I see it, Javascript tests should only perform checks related to it's functionality. Asserting visibility of static HTML elements does not fall under that.

**Comment by szymach** [comment]
I propose we simply remove these steps in tests requiring JavaScript. Headers are validated in other tests anyway, so we do not loose any coverage.

**Comment by szymach** [comment]
Unless we move a different testing tool, these errors will occur from time to time (hopefully less frequently now).
