### ISSUE TITLE
Remove szymach permission to write into this repo 

### ISSUE THREAD

**Issue by norzechowicz** [fsi-open/admin-bundle#249]
It's dangerous to allow @szymach write/push/merge into this repository.  
https://github.com/fsi-open/admin-bundle/pull/247#issuecomment-272187232 as I mentioned here he broke readme by removing spaces at the end of lines. Whats even better he pushed those changes into all branches, `2.0` (this one suppose to be frozen), `2.1` (and where is status of 2.1 build?) and `master` and now in order to fix that he gonna need to create a new PR and push it once again to all of those branches. 
It's only a matter of time when he will push something more destructive everywhere. I would really like to avoid forking all those repositories into another organization but it might be the only way, currently I'm afraid of executing `composer update` because of potential BC breaks

**Comment by szymach** [comment]
I was asked to do this by @chives.

**Comment by szymach** [comment]
Also, you yourself have been pushing non-reviewed PRs into master branches of fsi-open repositories, which contained errors (like [here](https://github.com/fsi-open/doctrine-extensions-bundle/pull/58/files), fixed [here](https://github.com/fsi-open/doctrine-extensions-bundle/pull/60/files) - not by you by the way). Not the only instance I remember, just can't find the other ones.

So perhaps you should not write angry issues if you don't even know what's happening.

**Comment by norzechowicz** [comment]
I was expecting such childish answer, good luck and feel free to do whatever you think is good for this project. Because there are projects that depends on it I had to fork it, stabilize and release under different organization.
