### ISSUE TITLE
Catch ForeignKeyConstraintViolationException during batch action processing

### ISSUE THREAD

**Issue by chives** [fsi-open/admin-bundle#297]
There could be another context and/or request handler for [doctrine delete element](https://github.com/fsi-open/admin-bundle/blob/master/Doctrine/Admin/DeleteElement.php) which wraps deleting objects in transaction and `try`/`catch` which catches `ForeignKeyConstraintViolationException` and adds some error message about deleting of objects that are used somewhere. Unfortunately only the first used object could be printed in that message because after throwing an exception the `EntityManager` is closed and cannot be used for further entity processing.

**Comment by szymach** [comment]
Still better to print one object instead of failing altogether with a 500 and potentially ending up with incorrect dataset.

**Comment by szymach** [comment]
The problem here is that the element does not have `FlashMessages` service to which we could pass the message. I do not think it is a good idea to add it to this class, perhaps we could add a context specific to Doctrine delete element which would handle the `try/catch`?
